version: "3.2"
services:
 backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: dockerfile
    volumes:
      - ./Backend/build/:/app/build
      - ./Backend/src/:/app/src
      - ./Backend/libraries/:/app/libraries
    env_file: ./Backend/.env
    ports:
      - 80:80
      - 8088:8088
    tty: true
    stdin_open: true
    links:
      - "database:database"
    depends_on:
      - database
    restart: always
    networks:
      networking:
        ipv4_address: 172.20.1.0

 database:
    container_name: database
    image: postgres:10.3
    env_file: ./Backend/.env
    volumes:
        - postgres:/data/postgres
        - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      networking:
        ipv4_address: 172.20.2.0
volumes:
  app:
    driver: Backend
  postgres:

networks:
  networking:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24