version: "3.2"
services:
 backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: dockerfile
    volumes:
      - ./Backend/build/:/app/build
      - ./Backend/src/:/app/src
      - ./Backend/libraries/:/app/libraries
    env_file: ./Backend/src/.env
    ports:
      - 80:80
      - 8088:8088
    tty: true
    stdin_open: true
    links:
      - "database"
    depends_on:
      - database
    restart: always
 database:
    container_name: database
    image: postgres:10.3
    env_file: ./Backend/src/.env
    volumes:
        - postgres:/data/postgres
        - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  app:
    driver: Backend
  postgres: