FROM debian:10-slim

WORKDIR /app

RUN apt update && \
    apt upgrade --yes && \
    apt install locales --yes && \
    dpkg-reconfigure tzdata

## INSTALL ESSENTIALS
RUN apt-get install --yes \
    build-essential \
    git \ 
    make \
    cmake \ 
    curl \
    pkg-config \
    zip \
    unzip \
    libssl-dev \
    openssl \
    python3 \
    librange-v3-dev \
    rapidjson-dev \
    ccache \
    zlib1g-dev \
    libjsoncpp-dev \
    uuid-dev \
    tar \
    libtool \
    musl-dev \
    medusa \
    libpq-dev \
    libc6-dev \
    postgresql \
    postgresql-contrib \
    lsof \
    botan

## MANAGER DEPENDENCIES
RUN rm -rf /var/lib/apt/lists/*

COPY Makefile .
# RUN make versioner_libs

# ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/src/test/